function F = EMSlev(airgap, intensity, pod)
% Computes the levitation force (N) of all the EMS units as a function of 
% their air gaps (mm) and intensities (A)
% ═════════════════════════════════════════════════════════════════════════
% Last updated: 15.12.2021
% ════════════════════════════════════════════════════════════════════════

x   = airgap(7:10);
y   = intensity(7:10);

F = pod.guiding.poly.p00 + ...
    pod.guiding.poly.p10.*x + ...
    pod.guiding.poly.p01.*y + ...
    pod.guiding.poly.p20.*x.^2 + ...
    pod.guiding.poly.p11.*x.*y + ...
    pod.guiding.poly.p02.*y.^2 + ...
    pod.guiding.poly.p21.*x.^2.*y + ...
    pod.guiding.poly.p12.*x.*y.^2 + ...
    pod.guiding.poly.p03.*y.^3;
